[package]
name = "sanction"
version = "0.2.0"
authors = ["John Wass <wassj@ctc.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
termimad = "0.9.5"
crossterm = "0.17.7"
git2 = "0.13"
glob = "0.3.0"
log = "0.4.11"
